### ISSUE TITLE
No auto-reload for a new rails 7 project

### ISSUE THREAD

**Issue by installero** [railsjazz/rails_live_reload#11]
Just a quick video:

https://youtu.be/Nj4KsL1FA98

```
Rails 7.0.3
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
```

**Comment by manastyretskyi** [comment]
Hello @installero,

Everything seems to be right, in that video when you start the server you can see what files are being watched.
<img width="677" alt="Screenshot 2022-06-11 at 7 44 39 PM" src="https://user-images.githubusercontent.com/43040379/173197018-acd88fca-277d-4011-b5b7-b79ec7de86cc.png">

In your case live reloading doesn't work because you are changing simple `html` file, which is not listened by default.
<img width="677" alt="Screenshot 2022-06-11 at 7 47 58 PM" src="https://user-images.githubusercontent.com/43040379/173197076-14510680-bd51-4c5b-b145-59bbf6c19df2.png">

You can change configuration to include html files as well, there is section in [README](https://github.com/railsjazz/rails_live_reload#create-initializer-configinitializersrails_live_reloadrb) for that.

**Comment by igorkasyanchuk** [comment]
We suggest you to use .erb as a template language since HTML is not suitable for Rails view.
Just in case you need to use it - please configure gem as mentioned above.

**Comment by installero** [comment]
Sorry, my bad 🤦‍♂️

Thank's for your work and for a quick reply. This gem seems to be useful!

**Comment by igorkasyanchuk** [comment]
Thanks, check more cool gems here https://www.railsjazz.com
