### ISSUE TITLE
Tailwindcss-rails Integration?

### ISSUE THREAD

**Issue by richjdsmith** [railsjazz/rails_live_reload#22]
Just wondering how/if this gem handles tailwindcss? At the moment I run rails tailwindcss:watch concurrently with my rails server. Would love to avoid that step. 

Fantastic gem by the way, really appreciate it!

**Comment by richjdsmith** [comment]
Answered my own question. As of now, the rails_live_reload doesn't recompile tailwindcss assets. Maybe add to the future updates list? I'll look into it and see if I can figure out how to add a PR.

**Comment by manastyretskyi** [comment]
Hello, as of right now we don’t want to add any functionality that would be specific to some CSS of JS frameworks, as it can be error-prone due to different setups, etc. The idea of the gem is that it's just listening to file changes, and reloads the page based on them, it doesn’t make any changes to the files, and it doesn’t tell you how this changes should be made, this is the only way for now that will allow gem to work with basically any assets setup

**Comment by richjdsmith** [comment]
Thanks for the comment @manastyretskyi , Would you consider some integration with [rails-tailwindcss ](https://github.com/rails/tailwindcss-rails) based on the fact that is included with rails/officially rails supported?

**Comment by manastyretskyi** [comment]
It's a tricky question, since [rails-tailwindcss](https://github.com/rails/tailwindcss-rails) is not the only 'official' way to add tailwindcss to rails app, there is also a [cssbundling-rails](https://github.com/rails/cssbundling-rails).
In my opinion it would make sense to make a direct integration in case it will improve work of the gem, for example, triggering refresh only after tailwindcss was compiled, but just integrating it to run `tailwindcss:watch` doesn't make sense in my opinion. It would be more logical to open an issue in [tailwindcss-rails](https://github.com/rails/tailwindcss-rails) and propose adding it there.
